version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: saida_material_postgres
    restart: always
    environment:
      POSTGRES_USER: saida_material_user
      POSTGRES_PASSWORD: saida_password
      POSTGRES_DB: saida_material_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: saida_material_backend
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/saida_material_db
      SPRING_DATASOURCE_USERNAME: saida_material_user
      SPRING_DATASOURCE_PASSWORD: saida_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

volumes:
  postgres_data: